# Generated by Django 3.2.4 on 2021-06-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('currency', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=20, max_digits=100)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('date', models.DateTimeField(verbose_name='transaction date')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=100)),
                ('price', models.DecimalField(decimal_places=4, max_digits=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costbasis.account')),
            ],
        ),
    ]
